# Generated by Django 5.1.15 on 2026-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('sale_created', 'Sale Created'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('stock_updated', 'Stock Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('category_created', 'Category Created')], max_length=50),
        ),
    ]
